### PR TITLE
STRB-461: add export from vault step

### PR DESCRIPTION
**Pull request by ddisch-ces**

### CODE REVIEW

**Comment by ddisch-ces** [comment]
@james-osgerby-coexservices you mind running your eyes over this?

**Comment by ddisch-ces** [comment]
@aconstanti-ces maybe you too?

**Review by james-osgerby-coexservices — APPROVED** [review]
This is going to be quite useful

The main thing I'd suggest we could improve is the policies for the github-actions-role and that stuff isn't in this repository

**Comment by ddisch-ces** [comment]
I suppose we should note that down for people who come back to this PR to understand it.

In order to allow the `VAULT_TOKEN` here to read from an application's vault KV storage the following policies need to be updated and applied: https://github.com/coexservices/oci-infra-vault/commit/bb4cfd418bd01dc2d225ffca155432296d234549

**Review by aconstanti-ces — APPROVED** [review]

**Pull request merged**
